sudo: false
dist: trusty
language: python

matrix:
  include:
    - python: 3.5
      env: TOXENV=check_readme
    - python: 3.5
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=solium
    - python: 3.5
      env: TOXENV=py35,coverage

install: .support/travis-install.sh

script: .support/travis-run.sh
