version: "3.9"

services:
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CLIENT_PASSWORDS=bitnami
      - KAFKA_CLIENT_USERS=user
    depends_on:
      - zookeeper

  redis:
    image: redis:latest
    ports:
      - 6379:6379

  
  gsy-market:
    image: ghcr.io/bc4p/gsy-e:latest
    build:
      context: .
      dockerfile: Dockerfile.bc
    command: run --setup bc4p.demonstration -t 30s -s 15m --enable-external-connection --start-date 2022-07-01 #--enable-bc --slot-length-realtime 10s 
    volumes:
      - ./gsy_e-simulation/:/app/gsy_e-simulation # ~/gsy_e-simulation
      - ./src/gsy_e/setup:/app/src/gsy_e/setup
      - ./gsy-framework/gsy_framework/influx_connection/resources:/app/gsy-framework/gsy_framework/influx_connection/resources
    environment:
      - KAFKA_URL=kafka:9092
      - KAFKA_USERNAME=user
      - KAFKA_PASSWORD=bitnami
      - KAFKA_COMMUNICATION_SECURITY_PROTOCOL=PLAINTEXT
      - REDIS_URL=redis://redis
    depends_on:
      - kafka
      - redis
#      - substrate1

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
