site_name: 'D3A'
site_description: 'Documentation for the D3A by Grid Singularity'
site_author: 'Grid Singularity'

nav:
- D3A Documentation:
    - 'Overview': 'd3a-documentation.md' 
    - 'User Interface (d3a.io)': 
        - 'UI Overview': 'user-interface-d3a.md' 
        - 'Projects (Home Page)': 'projects-home-page.md' 
        - 'Simulation Configuration': 
            - 'Simulation Configuration Overview': 'simulation-configuration.md' 
            - 'General Settings': 'general-settings.md' 
            - 'Grid Setup': 
                - 'Initial Grid Setup': 'grid-setup.md' 
                - 'PV': 'pv.md' 
                - 'Storage': 'storage.md' 
                - 'Load': 'load.md' 
                - 'Market Maker': 'market-maker.md'
                - 'Power Plant': 'power-plant.md' 
                - 'Areas': 'areas.md' 
            - 'Libraries': 'libraries.md' 
            - 'Upload File Formats': 'upload-file-formats.md' 
        - 'Results': 'results.md' 
    - 'Backend Codebase': 
        - 'Backend Codebase Overview': 'backend-codebase.md'  
        - 'Strategies': 
            - 'Load Strategy': 'load-strategy.md' 
            - 'Energy Storage System (ESS) Strategy': 'ess-strategy.md' 
            - 'PV Strategy': 'pv-strategy.md' 
            - 'Infinite Power Plant Strategy': 'infinite-power-plant-strategy.md' 
            - 'Custom Load Strategy': 'custom-load-strategy.md' 
            - 'Finite Power Plant Strategy': 'finite-power-plant-strategy.md' 
            - 'Custom PV Strategy': 'custom-pv-strategy.md' 
            - 'Infinite Bus Strategy': 'infinite-bus-strategy.md' 
            - 'How to Implement Custom Device Strategies': 'how-implement-custom-device-strategies.md' 
            - 'Market Maker Strategy': 'market-maker-strategy.md' 
            - 'How Strategies Adjust the Prices of Offers and Bids': 'how-strategies-adjust-prices.md' 
        - 'Markets': 
            - 'Markets Overview': 'markets.md' 
            - 'Balancing Market': 'balancing-market.md' 
            - 'Inter-Area Agent': 'inter-area-agent.md' 
            - 'Two Sided Pay-As-Clear': 'two-sided-pay-as-clear.md' 
            - 'One Sided Pay-As-Offer': 'one-sided-pay-as-offer.md' 
            - 'Two Sided Pay-As-Bid': 'two-sided-pay-as-bid.md' 
        - 'D3A Blockchain Support': 
            - 'D3A Blockchain Overview': 'd3a-blockchain-support.md' 
            - 'ClearingToken Smart Contract': 'clearingtoken-smart-contract.md' 
            - 'Market Smart Contract': 'market-smart-contract.md' 
            - 'Steps to Run D3A on Tobalaba': 'run-d3a-on-tobalaba.md' 
        - 'Simulation Results': 'simulation-results.md' 
        - 'Alternative Pricing Schemes': 'alternative-pricing-schemes.md' 
        - 'How to Configure Grid Transfer Fee': 'configure-transfer-fee.md'
        - 'Simulation Events': 'simulation-events.md' 
        - 'How to Create a setup-file': 'create-setup-file.md' 
        - 'How to Change Global Simulation Settings': 'change-global-sim-settings.md' 
        - 'How to launch Simulation via Command Line Interface (CLI)': 'launch-sim-via-cli.md' 
        - 'Installation Instructions': 'installation-instructions.md' 
        - 'Key Performance Indicators (KPIs)': 'kpis.md'                 
- FAQ: 'faq.md' 

# Configuration for the Material theme
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: 'en'
  palette:
    primary: 'white'
    accent: 'teal'
  font:
    text: 'PT Sans'
    code: 'Ubuntu Mono'
  favicon: 'img/d3a-logo.png'
  logo: 'img/d3a-logo.png'
  feature:
    tabs: false

# Extra css for further customization
extra_css:
  - 'stylesheets/extra.css'

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - https://research.web3.foundation/en/latest/mathjax-config.js

# Repository that houses the source code for this site. This
# is needed to render the nice GH link on the top right.
repo_name: 'D3A on github'
repo_url: 'https://github.com/gridsingularity/d3a'

# Social links
extra:
  social:
    - type: 'github'
      size: 'lg'
      link: 'https://github.com/gridsingularity'
    - type: 'twitter'
      size: 'lg'
      link: 'https://twitter.com/gridsingularity'
    - type: 'linkedin'
      size: 'lg'
      link: 'https://www.linkedin.com/company/grid-singularity'

footer:
  logo: 'img/d3a-logo.png'

markdown_extensions:
    - admonition
    - codehilite:
        guess_lang: false
    - toc:
        permalink: true
    - mdtooltips
