name: Deploy Docker

# Run workflow on tags starting with v (eg. v2, v1.2.0)
# on:
#   push:
#     tags:        
#       - v*

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
      
      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile.bc
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:bc-${{ github.ref }}
            ghcr.io/${{ github.repository }}:bc-latest

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v3
        with:
          push: true # Will only build if this is not here
          tags: |
            ghcr.io/${{ github.repository }}:${{ github.ref }}
            ghcr.io/${{ github.repository }}:latest