name: d3a-ci
on:
  pull_request:
    branches:
      - master
      - staging
      - feature/D3ASIM-3140
jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        TOXENV: ci
        TEST_ENV: $HOME/DIR
      run: |
        export TEST_VAR=$HOME/DIR
        echo $TEST_VAR
