name: d3a-ci-cd-staging
on:
  push:
    branches:
      - staging
jobs:
  test-build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      env:
        TOXENV: travis
      run: |
        bash .support/travis-install.sh
        bash .support/travis-run.sh
    - name: Trigger deployment
      shell: bash
      run: |
        curl -X POST --header "authorization: Bearer ${{ secrets.GSYDEV_TOKEN }}" \
        -H 'Accept: application/json' \
        https://api.github.com/repos/gridsingularity/d3a-web/actions/workflows/d3a-staging.yaml/dispatches \
        -d '{"ref":"refs/heads/master"}'
